import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
import pathlib
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QAbstractItemView

s = None
accounts = pathlib.Path("Accounts.db")
user = pathlib.Path("User.db")
lam = [[user, 0], [accounts, 1]]
for file in lam:
    print(file[0])
    if file[0].exists():
        print("File exist")
    elif file[1] == 0:
        print("check")
        print("Creating User.db")
        conn = sqlite3.connect('User.db')
        c = conn.cursor()
        c.execute(
            """CREATE TABLE security(ID INTEGER PRIMARY KEY,User string NOT NULL,Hash string NOT NULL,Topt string)""")
        conn.commit()
        conn.close()
    else:
        print("Creating Accounts.db")
        conn = sqlite3.connect('Accounts.db')
        c = conn.cursor()
        c.execute(
            """CREATE TABLE accounts(ID INTEGER PRIMARY KEY,Account string NOT NULL,User string NOT NULL,Hash string 
            NOT NULL,Date string NOT NULL,security_ID INTEGER)""")
        conn.commit()
        conn.close()


    class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(812, 553)

            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
            self.gridLayout.setObjectName("gridLayout")
            self.table_view = QtWidgets.QTableWidget(self.centralwidget)
            self.table_view.setEnabled(True)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.table_view.sizePolicy().hasHeightForWidth())
            self.table_view.setSizePolicy(sizePolicy)
            self.table_view.setMinimumSize(QtCore.QSize(520, 0))
            self.table_view.setMaximumSize(QtCore.QSize(100000, 100000))
            palette = QtGui.QPalette()
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(135, 206, 250))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(135, 206, 250))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
            brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
            self.table_view.setPalette(palette)
            self.table_view.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
            self.table_view.setLayoutDirection(QtCore.Qt.LeftToRight)
            self.table_view.setInputMethodHints(QtCore.Qt.ImhNone)
            self.table_view.setFrameShape(QtWidgets.QFrame.NoFrame)
            self.table_view.setFrameShadow(QtWidgets.QFrame.Plain)
            self.table_view.setLineWidth(0)
            self.table_view.setMidLineWidth(-1)
            self.table_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
            self.table_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
            self.table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
            self.table_view.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
            self.table_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
            self.table_view.setAlternatingRowColors(True)
            self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
            self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
            self.table_view.setTextElideMode(QtCore.Qt.ElideRight)
            self.table_view.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
            self.table_view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
            self.table_view.setGridStyle(QtCore.Qt.SolidLine)
            self.table_view.setCornerButtonEnabled(True)
            self.table_view.setRowCount(0)
            self.table_view.setColumnCount(4)

            self.table_view.setObjectName("table_view")
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setVerticalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setVerticalHeaderItem(1, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setVerticalHeaderItem(2, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setVerticalHeaderItem(3, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setHorizontalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setHorizontalHeaderItem(1, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setHorizontalHeaderItem(2, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setHorizontalHeaderItem(3, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(0, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(0, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(0, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(0, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(1, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(1, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(1, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(1, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(2, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(2, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(2, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(2, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(3, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(3, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(3, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.table_view.setItem(3, 3, item)
            self.table_view.horizontalHeader().setCascadingSectionResizes(False)
            self.table_view.horizontalHeader().setStretchLastSection(False)
            self.gridLayout.addWidget(self.table_view, 0, 0, 1, 2)
            self.grp_box_pgen = QtWidgets.QGroupBox(self.centralwidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.grp_box_pgen.sizePolicy().hasHeightForWidth())
            self.grp_box_pgen.setSizePolicy(sizePolicy)
            self.grp_box_pgen.setMinimumSize(QtCore.QSize(0, 111))
            self.grp_box_pgen.setAutoFillBackground(False)
            self.grp_box_pgen.setFlat(False)
            self.grp_box_pgen.setObjectName("grp_box_pgen")
            self.gridLayout_2 = QtWidgets.QGridLayout(self.grp_box_pgen)
            self.gridLayout_2.setObjectName("gridLayout_2")
            self.lbl_slen_pgen = QtWidgets.QLabel(self.grp_box_pgen)
            self.lbl_slen_pgen.setObjectName("lbl_slen_pgen")
            self.gridLayout_2.addWidget(self.lbl_slen_pgen, 0, 0, 1, 1)
            self.tbox_slen_pgen = QtWidgets.QLineEdit(self.grp_box_pgen)
            self.tbox_slen_pgen.setMinimumSize(QtCore.QSize(0, 20))
            self.tbox_slen_pgen.setFrame(True)
            self.tbox_slen_pgen.setObjectName("tbox_slen_pgen")
            self.gridLayout_2.addWidget(self.tbox_slen_pgen, 0, 1, 1, 2)
            self.btn_genpass = QtWidgets.QPushButton(self.grp_box_pgen)
            self.btn_genpass.setMinimumSize(QtCore.QSize(100, 23))
            self.btn_genpass.setObjectName("btn_genpass")
            self.gridLayout_2.addWidget(self.btn_genpass, 0, 3, 1, 1)
            self.lbl_genpass_pgen = QtWidgets.QLabel(self.grp_box_pgen)
            self.lbl_genpass_pgen.setObjectName("lbl_genpass_pgen")
            self.gridLayout_2.addWidget(self.lbl_genpass_pgen, 1, 0, 1, 1)
            self.btn_cpy_pass = QtWidgets.QPushButton(self.grp_box_pgen)
            self.btn_cpy_pass.setMinimumSize(QtCore.QSize(80, 23))
            self.btn_cpy_pass.setObjectName("btn_cpy_pass")
            self.gridLayout_2.addWidget(self.btn_cpy_pass, 2, 1, 1, 1)
            self.lbl_warn_pgen = QtWidgets.QLabel(self.grp_box_pgen)

            self.lbl_warn_pgen.setFrameShadow(QtWidgets.QFrame.Plain)
            self.lbl_warn_pgen.setTextFormat(QtCore.Qt.PlainText)
            self.lbl_warn_pgen.setObjectName("lbl_warn_pgen")
            self.gridLayout_2.addWidget(self.lbl_warn_pgen, 2, 2, 1, 2)
            self.tbox_genpass_pgen = QtWidgets.QLineEdit(self.grp_box_pgen)
            self.tbox_genpass_pgen.setMinimumSize(QtCore.QSize(242, 20))
            self.tbox_genpass_pgen.setFrame(True)
            self.tbox_genpass_pgen.setObjectName("tbox_genpass_pgen")
            self.gridLayout_2.addWidget(self.tbox_genpass_pgen, 1, 1, 1, 3)
            self.lbl_showpass_pgen = QtWidgets.QLabel(self.grp_box_pgen)
            self.lbl_showpass_pgen.setEnabled(True)
            self.lbl_showpass_pgen.setGeometry(QtCore.QRect(336, 52, 20, 20))
            self.lbl_showpass_pgen.setText("")
            self.lbl_showpass_pgen.setPixmap(QtGui.QPixmap("showpass.png"))
            self.lbl_showpass_pgen.setScaledContents(True)
            self.lbl_showpass_pgen.setObjectName("lbl_showpass_pgen")
            self.lbl_showpass_pgen.setStyleSheet("background-color: transparent\n")
            self.tbox_genpass_pgen.raise_()
            self.lbl_genpass_pgen.raise_()
            self.lbl_warn_pgen.raise_()
            self.btn_genpass.raise_()
            self.lbl_slen_pgen.raise_()
            self.tbox_slen_pgen.raise_()
            self.btn_cpy_pass.raise_()
            self.lbl_showpass_pgen.raise_()
            self.gridLayout.addWidget(self.grp_box_pgen, 2, 0, 1, 1)
            self.widget_misc = QtWidgets.QWidget(self.centralwidget)
            self.widget_misc.setObjectName("widget_misc")
            self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_misc)
            self.verticalLayout.setObjectName("verticalLayout")
            self.btn_logout = QtWidgets.QPushButton(self.widget_misc)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.btn_logout.sizePolicy().hasHeightForWidth())
            self.btn_logout.setSizePolicy(sizePolicy)
            self.btn_logout.setMinimumSize(QtCore.QSize(0, 23))
            self.btn_logout.setMaximumSize(QtCore.QSize(126, 16777215))
            self.btn_logout.setObjectName("btn_logout")
            self.verticalLayout.addWidget(self.btn_logout)
            self.gridLayout.addWidget(self.widget_misc, 2, 1, 1, 1)
            self.stk_user = QtWidgets.QStackedWidget(self.centralwidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.stk_user.sizePolicy().hasHeightForWidth())
            self.stk_user.setSizePolicy(sizePolicy)
            self.stk_user.setMinimumSize(QtCore.QSize(0, 340))
            self.stk_user.setObjectName("stk_user")
            self.page_3 = QtWidgets.QWidget()
            self.page_3.setObjectName("page_3")
            self.tab_login = QtWidgets.QTabWidget(self.page_3)
            self.tab_login.setGeometry(QtCore.QRect(0, 0, 265, 141))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.tab_login.sizePolicy().hasHeightForWidth())
            self.tab_login.setSizePolicy(sizePolicy)
            self.tab_login.setMinimumSize(QtCore.QSize(0, 0))
            palette = QtGui.QPalette()
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
            self.tab_login.setPalette(palette)
            self.tab_login.setAutoFillBackground(False)

            self.tab_login.setObjectName("tab_login")
            self.tab = QtWidgets.QWidget()
            self.tab.setObjectName("tab")

            self.stk_login = QtWidgets.QStackedWidget(self.tab)
            self.stk_login.setGeometry(QtCore.QRect(3, 3, 261, 111))
            self.stk_login.setObjectName("stk_login")
            self.page_8 = QtWidgets.QWidget()
            self.page_8.setObjectName("page_8")
            self.lbl_user_login = QtWidgets.QLabel(self.page_8)
            self.lbl_user_login.setGeometry(QtCore.QRect(9, 9, 48, 16))
            self.lbl_user_login.setObjectName("lbl_user_login")
            self.tbox_user_login = QtWidgets.QLineEdit(self.page_8)
            self.tbox_user_login.setGeometry(QtCore.QRect(63, 9, 184, 20))
            self.tbox_user_login.setFrame(True)
            self.tbox_user_login.setObjectName("tbox_user_login")
            self.lbl_pass_login = QtWidgets.QLabel(self.page_8)
            self.lbl_pass_login.setGeometry(QtCore.QRect(9, 35, 46, 16))
            self.lbl_pass_login.setObjectName("lbl_pass_login")
            self.tbox_pass_login = QtWidgets.QLineEdit(self.page_8)
            self.tbox_pass_login.setGeometry(QtCore.QRect(63, 35, 184, 20))
            self.tbox_pass_login.setFrame(True)
            self.tbox_pass_login.setObjectName("tbox_pass_login")
            self.btn_login = QtWidgets.QPushButton(self.page_8)
            self.btn_login.setGeometry(QtCore.QRect(10, 64, 241, 23))
            self.btn_login.setMinimumSize(QtCore.QSize(0, 23))
            self.btn_login.setObjectName("btn_login")
            self.lbl_warn_login = QtWidgets.QLabel(self.page_8)
            self.lbl_warn_login.setGeometry(QtCore.QRect(10, 87, 241, 16))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lbl_warn_login.sizePolicy().hasHeightForWidth())
            self.lbl_warn_login.setSizePolicy(sizePolicy)

            self.lbl_warn_login.setTextFormat(QtCore.Qt.PlainText)
            self.lbl_warn_login.setObjectName("lbl_warn_login")
            self.lbl_showpass_login = QtWidgets.QLabel(self.page_8)
            self.lbl_showpass_login.setEnabled(True)
            self.lbl_showpass_login.setGeometry(QtCore.QRect(224, 35, 21, 20))
            self.lbl_showpass_login.setText("")
            self.lbl_showpass_login.setPixmap(QtGui.QPixmap("showpass.png"))
            self.lbl_showpass_login.setScaledContents(True)
            self.lbl_showpass_login.setObjectName("lbl_showpass_login")
            self.lbl_showpass_login.setStyleSheet("background-color: transparent\n")
            self.stk_login.addWidget(self.page_8)

            self.page_9 = QtWidgets.QWidget()
            self.page_9.setObjectName("page_9")
            self.lbl_otp_login = QtWidgets.QLabel(self.page_9)
            self.lbl_otp_login.setGeometry(QtCore.QRect(9, 9, 48, 40))
            self.lbl_otp_login.setFont(QFont("", 17))
            self.lbl_otp_login.setObjectName("lbl_otp_login")
            self.tbox_otp_login = QtWidgets.QLineEdit(self.page_9)
            self.tbox_otp_login.setGeometry(QtCore.QRect(63, 9, 184, 40))
            self.tbox_otp_login.setFrame(True)
            self.tbox_otp_login.setObjectName("tbox_otp_login")
            self.tbox_otp_login.setFont(QFont("", 17))
            self.btn_submit_login = QtWidgets.QPushButton(self.page_9)
            self.btn_submit_login.setGeometry(QtCore.QRect(10, 58, 241, 25))
            self.btn_submit_login.setMinimumSize(QtCore.QSize(0, 23))
            self.btn_submit_login.setObjectName("btn_submit_login")
            self.btn_submit_login.setFont(QFont("", 14))
            self.stk_login.addWidget(self.page_9)

            self.tab_login.addTab(self.tab, "")
            self.tab_2 = QtWidgets.QWidget()
            self.tab_2.setObjectName("tab_2")

            self.stk_signup = QtWidgets.QStackedWidget(self.tab_2)
            self.stk_signup.setGeometry(QtCore.QRect(3, 3, 261, 157))
            self.stk_signup.setObjectName("stk_signup")
            self.page_10 = QtWidgets.QWidget()
            self.page_10.setObjectName("page_10")
            self.lbl_user_signup = QtWidgets.QLabel(self.page_10)
            self.lbl_user_signup.setGeometry(QtCore.QRect(9, 9, 48, 16))
            self.lbl_user_signup.setObjectName("lbl_user_signup")
            self.tbox_user_signup = QtWidgets.QLineEdit(self.page_10)
            self.tbox_user_signup.setGeometry(QtCore.QRect(76, 9, 171, 20))
            self.tbox_user_signup.setInputMask("")
            self.tbox_user_signup.setFrame(True)
            self.tbox_user_signup.setObjectName("tbox_user_signup")
            self.lbl_pass_signup = QtWidgets.QLabel(self.page_10)
            self.lbl_pass_signup.setGeometry(QtCore.QRect(9, 35, 46, 16))
            self.lbl_pass_signup.setObjectName("lbl_pass_signup")
            self.tbox_pass_signup = QtWidgets.QLineEdit(self.page_10)
            self.tbox_pass_signup.setGeometry(QtCore.QRect(76, 35, 171, 20))
            self.tbox_pass_signup.setInputMask("")
            self.tbox_pass_signup.setFrame(True)
            self.tbox_pass_signup.setObjectName("tbox_pass_signup")
            self.lbl_repass_signup = QtWidgets.QLabel(self.page_10)
            self.lbl_repass_signup.setGeometry(QtCore.QRect(9, 61, 61, 16))
            self.lbl_repass_signup.setObjectName("lbl_repass_signup")
            self.tbox_repass_signup = QtWidgets.QLineEdit(self.page_10)
            self.tbox_repass_signup.setGeometry(QtCore.QRect(76, 61, 171, 20))
            self.tbox_repass_signup.setFrame(True)
            self.tbox_repass_signup.setObjectName("tbox_repass_signup")
            self.chkbox_2fa_signup = QtWidgets.QCheckBox(self.page_10)
            self.chkbox_2fa_signup.setGeometry(QtCore.QRect(76, 86, 100, 17))
            self.chkbox_2fa_signup.setLayoutDirection(QtCore.Qt.LeftToRight)
            self.chkbox_2fa_signup.setChecked(True)
            self.chkbox_2fa_signup.setTristate(False)
            self.chkbox_2fa_signup.setObjectName("chkbox_2fa_signup")
            self.btn_signup = QtWidgets.QPushButton(self.page_10)
            self.btn_signup.setGeometry(QtCore.QRect(9, 107, 241, 23))
            self.btn_signup.setCheckable(False)
            self.btn_signup.setFlat(False)
            self.btn_signup.setObjectName("btn_signup")
            self.lbl_warn_signup = QtWidgets.QLabel(self.page_10)
            self.lbl_warn_signup.setGeometry(QtCore.QRect(8, 131, 241, 20))

            self.lbl_warn_signup.setTextFormat(QtCore.Qt.PlainText)
            self.lbl_warn_signup.setObjectName("lbl_warn_signup")

            self.lbl_showpass1_signup = QtWidgets.QLabel(self.page_10)
            self.lbl_showpass1_signup.setEnabled(True)
            self.lbl_showpass1_signup.setGeometry(QtCore.QRect(224, 35, 21, 20))
            self.lbl_showpass1_signup.setText("")
            self.lbl_showpass1_signup.setPixmap(QtGui.QPixmap("showpass.png"))
            self.lbl_showpass1_signup.setScaledContents(True)
            self.lbl_showpass1_signup.setObjectName("lbl_showpass1_signup")
            self.lbl_showpass1_signup.setStyleSheet("background-color: transparent\n")
            self.lbl_showpass2_signup = QtWidgets.QLabel(self.page_10)
            self.lbl_showpass2_signup.setEnabled(True)
            self.lbl_showpass2_signup.setGeometry(QtCore.QRect(224, 61, 21, 20))
            self.lbl_showpass2_signup.setText("")
            self.lbl_showpass2_signup.setPixmap(QtGui.QPixmap("showpass.png"))
            self.lbl_showpass2_signup.setScaledContents(True)
            self.lbl_showpass2_signup.setObjectName("lbl_showpass2_signup")
            self.lbl_showpass2_signup.setStyleSheet("background-color: transparent\n")
            self.stk_signup.addWidget(self.page_10)

            self.page_11 = QtWidgets.QWidget()
            self.page_11.setObjectName("page_11")
            self.lbl_qr_signup = QtWidgets.QLabel(self.page_11)
            self.lbl_qr_signup.setGeometry(QtCore.QRect(8, 8, 242, 242))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lbl_qr_signup.sizePolicy().hasHeightForWidth())
            self.lbl_qr_signup.setSizePolicy(sizePolicy)
            self.lbl_qr_signup.setMinimumSize(QtCore.QSize(0, 0))
            self.lbl_qr_signup.setMaximumSize(QtCore.QSize(251, 251))
            self.lbl_qr_signup.setText("")
            self.lbl_qr_signup.setPixmap(
                QtGui.QPixmap("C:\\Users\\Leader\\Desktop\\../Pictures/Screenshots/Screenshot (1).png"))
            self.lbl_qr_signup.setScaledContents(True)
            self.lbl_qr_signup.setObjectName("lbl_qr_signup")
            self.btn_signup_done = QtWidgets.QPushButton(self.page_11)
            self.btn_signup_done.setGeometry(QtCore.QRect(8, 263, 241, 23))
            self.btn_signup_done.setCheckable(False)
            self.btn_signup_done.setFlat(False)
            self.stk_signup.addWidget(self.page_11)

            self.tab_login.addTab(self.tab_2, "")
            self.stk_user.addWidget(self.page_3)
            self.page_4 = QtWidgets.QWidget()
            self.page_4.setObjectName("page_4")
            self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_4)
            self.verticalLayout_3.setObjectName("verticalLayout_3")
            self.grp_box_add = QtWidgets.QGroupBox(self.page_4)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.grp_box_add.sizePolicy().hasHeightForWidth())
            self.grp_box_add.setSizePolicy(sizePolicy)
            self.grp_box_add.setMinimumSize(QtCore.QSize(0, 0))
            self.grp_box_add.setAutoFillBackground(False)
            self.grp_box_add.setObjectName("grp_box_add")
            self.formLayout = QtWidgets.QFormLayout(self.grp_box_add)
            self.formLayout.setObjectName("formLayout")
            self.lbl_acc_add = QtWidgets.QLabel(self.grp_box_add)
            self.lbl_acc_add.setObjectName("lbl_acc_add")
            self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_acc_add)
            self.tbox_acc_add = QtWidgets.QLineEdit(self.grp_box_add)
            self.tbox_acc_add.setMinimumSize(QtCore.QSize(0, 20))
            self.tbox_acc_add.setFrame(True)
            self.tbox_acc_add.setObjectName("tbox_acc_add")
            self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tbox_acc_add)
            self.lbl_user_add = QtWidgets.QLabel(self.grp_box_add)
            self.lbl_user_add.setObjectName("lbl_user_add")
            self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_user_add)
            self.tbox_user_add = QtWidgets.QLineEdit(self.grp_box_add)
            self.tbox_user_add.setMinimumSize(QtCore.QSize(0, 20))
            self.tbox_user_add.setObjectName("tbox_user_add")
            self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tbox_user_add)
            self.lbl_pass_add = QtWidgets.QLabel(self.grp_box_add)
            self.lbl_pass_add.setObjectName("lbl_pass_add")
            self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_pass_add)
            self.tbox_pass_add = QtWidgets.QLineEdit(self.grp_box_add)
            self.tbox_pass_add.setMinimumSize(QtCore.QSize(0, 20))
            self.tbox_pass_add.setObjectName("tbox_pass_add")
            self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tbox_pass_add)
            self.btn_save_add = QtWidgets.QPushButton(self.grp_box_add)
            self.btn_save_add.setMinimumSize(QtCore.QSize(0, 23))
            self.btn_save_add.setDefault(False)
            self.btn_save_add.setObjectName("btn_save_add")
            self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.btn_save_add)
            self.lbl_warn_add = QtWidgets.QLabel(self.grp_box_add)

            self.lbl_warn_add.setTextFormat(QtCore.Qt.PlainText)
            self.lbl_warn_add.setObjectName("lbl_warn_add")
            self.lbl_warn_add.setMinimumWidth(230)
            self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.lbl_warn_add)
            self.lbl_showpass_add = QtWidgets.QLabel(self.grp_box_add)
            self.lbl_showpass_add.setEnabled(True)
            self.lbl_showpass_add.setGeometry(QtCore.QRect(217, 75, 21, 20))
            self.lbl_showpass_add.setText("")
            self.lbl_showpass_add.setPixmap(QtGui.QPixmap("showpass.png"))
            self.lbl_showpass_add.setScaledContents(True)
            self.lbl_showpass_add.setObjectName("lbl_showpass_add")
            self.lbl_showpass_add.setStyleSheet("background-color: transparent\n")
            self.tbox_pass_add.raise_()
            self.lbl_acc_add.raise_()
            self.tbox_acc_add.raise_()
            self.lbl_user_add.raise_()
            self.tbox_user_add.raise_()
            self.lbl_pass_add.raise_()
            self.btn_save_add.raise_()
            self.lbl_warn_add.raise_()
            self.lbl_showpass_add.raise_()
            self.verticalLayout_3.addWidget(self.grp_box_add)
            self.stk_action = QtWidgets.QStackedWidget(self.page_4)

            palette = QtGui.QPalette()
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
            brush.setStyle(QtCore.Qt.NoBrush)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
            brush.setStyle(QtCore.Qt.NoBrush)
            palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
            brush.setStyle(QtCore.Qt.NoBrush)
            palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)

            self.stk_user.addWidget(self.page_4)
            self.gridLayout.addWidget(self.stk_user, 0, 3, 1, 1)
            self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
            self.progressBar.setSizePolicy(sizePolicy)
            self.progressBar.setMaximumSize(QtCore.QSize(16777215, 3))

            self.progressBar.setTextVisible(False)
            self.progressBar.setInvertedAppearance(False)
            self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
            self.progressBar.setObjectName("progressBar")
            self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 2)
            self.widget_2 = QtWidgets.QWidget(self.centralwidget)
            self.widget_2.setObjectName("widget_2")
            self.listWidget = QtWidgets.QListWidget(self.widget_2)
            self.listWidget.setGeometry(QtCore.QRect(0, 0, 268, 111))
            self.listWidget.setObjectName("listWidget")
            item = QtWidgets.QListWidgetItem()
            self.listWidget.addItem(item)

            self.gridLayout.addWidget(self.widget_2, 2, 3, 1, 1)
            MainWindow.setCentralWidget(self.centralwidget)
            self.menubar = QtWidgets.QMenuBar(MainWindow)
            self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 21))

            self.menubar.setDefaultUp(False)
            self.menubar.setNativeMenuBar(True)
            self.menubar.setObjectName("menubar")
            self.menuFile = QtWidgets.QMenu(self.menubar)
            self.menuFile.setStyleSheet("")
            self.menuFile.setObjectName("menuFile")
            self.menuImport_CSV = QtWidgets.QMenu(self.menuFile)
            self.menuImport_CSV.setObjectName("menuImport_CSV")
            self.menuImport_Db = QtWidgets.QMenu(self.menuFile)
            self.menuImport_Db.setObjectName("menuImport_Db")
            self.menuHelp = QtWidgets.QMenu(self.menubar)
            self.menuHelp.setObjectName("menuHelp")
            self.menuSettings = QtWidgets.QMenu(self.menubar)
            self.menuSettings.setObjectName("menuSettings")
            self.menuTheme = QtWidgets.QMenu(self.menuSettings)
            self.menuTheme.setObjectName("menuTheme")
            self.menuAccount = QtWidgets.QMenu(self.menuSettings)
            self.menuAccount.setObjectName("menuAccount")
            MainWindow.setMenuBar(self.menubar)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)
            self.statusbar.hide()
            self.acnExport_db = QtWidgets.QAction(MainWindow)
            self.acnExport_db.setObjectName("acnExport_db")
            self.acnRefresh_db = QtWidgets.QAction(MainWindow)
            self.acnRefresh_db.setObjectName("acnRefresh_db")
            self.acnLogout = QtWidgets.QAction(MainWindow)
            self.acnLogout.setObjectName("acnLogout")
            self.acnDel_mainacc = QtWidgets.QAction(MainWindow)
            self.acnDel_mainacc.setObjectName("acnDel_mainacc")
            self.acnExit = QtWidgets.QAction(MainWindow)
            self.acnExit.setObjectName("acnExit")
            self.acnFigure_It_Yourself = QtWidgets.QAction(MainWindow)
            self.acnFigure_It_Yourself.setObjectName("acnFigure_It_Yourself")
            self.acnDark = QtWidgets.QAction(MainWindow)
            self.acnDark.setObjectName("acnDark")
            self.acnLight = QtWidgets.QAction(MainWindow)
            self.acnLight.setObjectName("acnLight")
            self.acnDefault = QtWidgets.QAction(MainWindow)
            self.acnDefault.setObjectName("acnDefault")
            self.actionAdd_2FA = QtWidgets.QAction(MainWindow)
            self.actionAdd_2FA.setObjectName("actionAdd_2FA")
            self.acnAdd_2FA = QtWidgets.QAction(MainWindow)
            self.acnAdd_2FA.setObjectName("acnAdd_2FA")
            self.acnCng_username = QtWidgets.QAction(MainWindow)
            self.acnCng_username.setObjectName("acnCng_username")
            self.acnCng_masterpass = QtWidgets.QAction(MainWindow)
            self.acnCng_masterpass.setObjectName("acnCng_masterpass")
            self.acnDel_2FA = QtWidgets.QAction(MainWindow)
            self.acnDel_2FA.setObjectName("acnDel_2FA")
            self.acnExport_CSV = QtWidgets.QAction(MainWindow)
            self.acnExport_CSV.setObjectName("acnExport_CSV")
            self.acnDb_New_Acc = QtWidgets.QAction(MainWindow)
            self.acnDb_New_Acc.setObjectName("acnDb_New_Acc")
            self.acnDb_Update_Acc = QtWidgets.QAction(MainWindow)
            self.acnDb_Update_Acc.setObjectName("acnDb_Update_Acc")
            self.acnCsv_New_Acc = QtWidgets.QAction(MainWindow)
            self.acnCsv_New_Acc.setObjectName("acnCsv_New_Acc")
            self.acnCsv_Update_Acc = QtWidgets.QAction(MainWindow)
            self.acnCsv_Update_Acc.setObjectName("acnCsv_Update_Acc")
            self.menuImport_CSV.addAction(self.acnCsv_New_Acc)
            self.menuImport_CSV.addAction(self.acnCsv_Update_Acc)
            self.menuImport_Db.addAction(self.acnDb_New_Acc)
            self.menuImport_Db.addAction(self.acnDb_Update_Acc)
            self.menuFile.addAction(self.menuImport_Db.menuAction())
            self.menuFile.addAction(self.menuImport_CSV.menuAction())
            self.menuFile.addSeparator()
            self.menuFile.addAction(self.acnExport_db)
            self.menuFile.addAction(self.acnExport_CSV)
            self.menuFile.addSeparator()
            self.menuFile.addAction(self.acnRefresh_db)
            self.menuFile.addSeparator()
            self.menuFile.addAction(self.acnLogout)
            self.menuFile.addAction(self.acnExit)
            self.menuHelp.addAction(self.acnFigure_It_Yourself)
            self.menuTheme.addAction(self.acnDefault)
            self.menuTheme.addAction(self.acnLight)
            self.menuTheme.addAction(self.acnDark)
            self.menuAccount.addAction(self.acnAdd_2FA)
            self.menuAccount.addAction(self.acnDel_2FA)
            self.menuAccount.addSeparator()
            self.menuAccount.addAction(self.acnCng_username)
            self.menuAccount.addAction(self.acnCng_masterpass)
            self.menuAccount.addSeparator()
            self.menuAccount.addAction(self.acnDel_mainacc)
            self.menuSettings.addAction(self.menuTheme.menuAction())
            self.menuSettings.addAction(self.menuAccount.menuAction())
            self.menubar.addAction(self.menuFile.menuAction())
            self.menubar.addAction(self.menuSettings.menuAction())
            self.menubar.addAction(self.menuHelp.menuAction())
            self.tbox_pass_add.setEchoMode(QtWidgets.QLineEdit.Password)  # password protected text

            self.tbox_pass_login.setEchoMode(QtWidgets.QLineEdit.Password)  # password protected text
            self.tbox_pass_signup.setEchoMode(QtWidgets.QLineEdit.Password)  # password protected text
            self.tbox_genpass_pgen.setEchoMode(QtWidgets.QLineEdit.Password)  # password protected text
            self.tbox_repass_signup.setEchoMode(QtWidgets.QLineEdit.Password)  # password protected text
            self.retranslateUi(MainWindow)
            self.stk_user.setCurrentIndex(0)
            self.tab_login.setCurrentIndex(0)
            self.stk_action.setCurrentIndex(0)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "OnePassGo! - Password Manager"))
            MainWindow.setWindowIcon(QtGui.QIcon('lock-icon.png'))
            self.table_view.setSortingEnabled(True)
            item = self.table_view.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "Account Name"))
            item = self.table_view.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "User Name"))
            item = self.table_view.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "Password"))
            item = self.table_view.horizontalHeaderItem(3)
            item.setText(_translate("MainWindow", "Date Created"))
            __sortingEnabled = self.table_view.isSortingEnabled()
            self.table_view.setSortingEnabled(False)
            self.table_view.setSortingEnabled(__sortingEnabled)
            self.grp_box_pgen.setTitle(_translate("MainWindow", "PassWord Generator"))
            self.lbl_slen_pgen.setText(_translate("MainWindow", "String Length"))
            self.tbox_slen_pgen.setPlaceholderText(_translate("MainWindow", "8"))
            self.btn_genpass.setText(_translate("MainWindow", "Generate Password"))
            self.lbl_genpass_pgen.setText(_translate("MainWindow", "Generated Password"))
            self.btn_cpy_pass.setText(_translate("MainWindow", "Copy Password"))
            self.tbox_genpass_pgen.setPlaceholderText(_translate("MainWindow", "●●●●●●●●●●"))

            self.btn_logout.setText(_translate("MainWindow", "Logout"))
            self.lbl_user_login.setText(_translate("MainWindow", "Username"))
            self.lbl_otp_login.setText(_translate("MainWindow", "OTP"))
            self.tbox_user_login.setPlaceholderText(_translate("MainWindow", " qwe123"))
            self.lbl_pass_login.setText(_translate("MainWindow", "Password"))
            self.tbox_pass_login.setPlaceholderText(_translate("MainWindow", "●●●●●●●●●●"))
            self.btn_login.setText(_translate("MainWindow", "Login"))
            self.btn_submit_login.setText(_translate("MainWindow", "Submit"))
            self.tab_login.setTabText(self.tab_login.indexOf(self.tab), _translate("MainWindow", "Login"))
            self.lbl_user_signup.setText(_translate("MainWindow", "Username"))
            self.tbox_user_signup.setPlaceholderText(_translate("MainWindow", " qwe123"))
            self.lbl_pass_signup.setText(_translate("MainWindow", "Password"))
            self.tbox_pass_signup.setPlaceholderText(_translate("MainWindow", "●●●●●●●●●●"))
            self.lbl_repass_signup.setText(_translate("MainWindow", "Retype-Pass"))
            self.tbox_repass_signup.setPlaceholderText(_translate("MainWindow", "●●●●●●●●●●"))
            self.chkbox_2fa_signup.setText(_translate("MainWindow", "Enable OTP 2FA"))
            self.btn_signup.setText(_translate("MainWindow", "SignUp"))
            self.btn_signup_done.setText(_translate("MainWindow", "Done"))
            self.tab_login.setTabText(self.tab_login.indexOf(self.tab_2), _translate("MainWindow", "New User"))
            self.grp_box_add.setTitle(_translate("MainWindow", "Add Account"))
            self.lbl_acc_add.setText(_translate("MainWindow", "Account Name"))
            self.tbox_acc_add.setPlaceholderText(_translate("MainWindow", "Google / Facebook"))
            self.lbl_user_add.setText(_translate("MainWindow", "User_Name"))
            self.tbox_user_add.setPlaceholderText(_translate("MainWindow", "qwe123"))
            self.lbl_pass_add.setText(_translate("MainWindow", "Password"))
            self.tbox_pass_add.setPlaceholderText(_translate("MainWindow", "●●●●●●●●●●"))
            self.btn_save_add.setText(_translate("MainWindow", "Save"))

            __sortingEnabled = self.listWidget.isSortingEnabled()
            self.listWidget.setSortingEnabled(False)
            header = self.table_view.horizontalHeader()
            header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
            header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
            header.setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
            header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)

            item = self.listWidget.item(0)
            item.setText(_translate("MainWindow", "Made By #16 (AKA Team_NOOBS)"))

            self.listWidget.scrollToBottom()
            self.listWidget.setSortingEnabled(__sortingEnabled)
            self.menuFile.setTitle(_translate("MainWindow", "File"))
            self.menuImport_CSV.setTitle(_translate("MainWindow", "Import CSV"))
            self.menuImport_Db.setTitle(_translate("MainWindow", "Import DataBase"))
            self.menuHelp.setTitle(_translate("MainWindow", "Help"))
            self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
            self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
            self.menuAccount.setTitle(_translate("MainWindow", "Account"))
            self.acnExport_db.setText(_translate("MainWindow", "Export Database"))
            self.acnRefresh_db.setText(_translate("MainWindow", "Refresh Database"))
            self.acnLogout.setText(_translate("MainWindow", "Logout"))
            self.acnDel_mainacc.setText(_translate("MainWindow", "Delete Main Account"))
            self.acnExit.setText(_translate("MainWindow", "Logout And Exit"))
            self.acnFigure_It_Yourself.setText(_translate("MainWindow", "Figure It Yourself"))
            self.acnDark.setText(_translate("MainWindow", "Dark"))
            self.acnLight.setText(_translate("MainWindow", "Light"))
            self.acnDefault.setText(_translate("MainWindow", "Default"))
            self.actionAdd_2FA.setText(_translate("MainWindow", "Add 2FA"))
            self.acnAdd_2FA.setText(_translate("MainWindow", "Add 2FA"))
            self.acnCng_username.setText(_translate("MainWindow", "Change Username"))
            self.acnCng_masterpass.setText(_translate("MainWindow", "Change Master Password"))
            self.acnDel_2FA.setText(_translate("MainWindow", "Delete 2FA"))
            self.acnExport_CSV.setText(_translate("MainWindow", "Export CSV"))
            self.acnDb_New_Acc.setText(_translate("MainWindow", "New Account"))
            self.acnDb_Update_Acc.setText(_translate("MainWindow", "Update Account"))
            self.acnCsv_New_Acc.setText(_translate("MainWindow", "New Account"))
            self.acnCsv_Update_Acc.setText(_translate("MainWindow", "Update Account"))
